# Site settings

# Name of your site (displayed in the header)
name: Martin Kuba

title: Martin Kuba
email: martin@martinkuba.com

description: Software Developer

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.martinkuba.com" # the base hostname & protocol for your site

twitter_username: martin_kuba
github_username:  martinkuba

# Build settings
markdown: kramdown
