# Site settings

# Name of your site (displayed in the header)
name: Martin Kuba

title: Martin Kuba
email: martin@martinkuba.com

description: Software Developer

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://martinkuba.github.io" # the base hostname & protocol for your site

twitter_username: martin_kuba
github_username:  martinkuba

# Build settings
markdown: kramdown

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: martinkuba

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-47902464-2